routes/web.php
<?php

use App\Http\Controllers\Account\SettingsController;
use App\Http\Controllers\Auth\SocialiteLoginController;
use App\Http\Controllers\Documentation\ReferencesController;
use App\Http\Controllers\Logs\AuditLogsController;
use App\Http\Controllers\Logs\SystemLogsController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Backend\UsersController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\BackendController;
use App\Http\Controllers\CustomerUrlController;
use App\Http\Controllers\Backend\Reports;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Backend\PermissionController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return redirect('index');
// });

$menu = theme()->getMenu();
array_walk($menu, function ($val) {
    if (isset($val['path'])) {
        $route = Route::get($val['path'], [PagesController::class, 'index']);

        // Exclude documentation from auth middleware
        if (!Str::contains($val['path'], 'documentation')) {
            $route->middleware('auth');
        }
    }
});

// Documentations pages
Route::prefix('documentation')->group(function () {
    Route::get('getting-started/references', [ReferencesController::class, 'index']);
    Route::get('getting-started/changelog', [PagesController::class, 'index']);
});

// Route::get('customer/{id}/{token}', [BackendController::class, 'customer'])
//                 ->name('customer');

Route::middleware('auth')->group(function () {
    Route::group(['middleware' => 'customAuth'], function () {
        // Account pages
        Route::prefix('account')->group(function () {
            Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
            Route::put('settings', [SettingsController::class, 'update'])->name('settings.update');
            Route::put('settings/email', [SettingsController::class, 'changeEmail'])->name('settings.changeEmail');
            Route::put('settings/password', [SettingsController::class, 'changePassword'])->name('settings.changePassword');
        });

        // Logs pages
        Route::prefix('log')->name('log.')->group(function () {
            Route::resource('system', SystemLogsController::class)->only(['index', 'destroy']);
            Route::resource('audit', AuditLogsController::class)->only(['index', 'destroy']);
        });

        //Orders Listing Page...
        Route::prefix('orders')->group(function () {
            Route::get('orders-list',  [OrderController::class, 'index'])->name('orders.index');
        });

        //Users Page...
        Route::resource('users', UsersController::class);

        //Roles Page...
        Route::resource('roles', RoleController::class);

        Route::get(
            'add-permissions/{id}',
            [RoleController::class, 'addPermissions']
        )
        ->name('roles.add_permissions');
        
        Route::get(
                'update-permissions/{id}',
                [RoleController::class, 'updatePermissions']
            )
            ->name('roles.update_permissions');
        
        Route::post(
                'add-role-permissions',
                [RoleController::class, 'addRolePermissions']
            );
        
        Route::post(
                'update-role-permissions',
                [RoleController::class, 'updateRolePermissions']
            );
    
        Route::post(
            'send-qvp-mail',
            [Reports::class, 'SendQvpMail']
        );

    });
});
// Route::resource('users', UsersController::class);

Route::get(
    'customer-preview/{public_key}/{token}', 
    [CustomerUrlController::class, 'index']
)
->name('customer-url');

//Check For Auth User...
// Route::group(['middleware' => 'customAuth'], function () {
//     Route::get('/dashboard',  [App\Http\Controllers\Backend\BackendController::class, 'index'])->name('dashboard');
//     Route::get('logout',  [App\Http\Controllers\Backend\BackendController::class, 'logout'])->name('logout');
    
// });

/**
 * Socialite login using Google service
 * https://laravel.com/docs/8.x/socialite
 */
Route::get('/auth/redirect/{provider}', [SocialiteLoginController::class, 'redirect']);

require __DIR__.'/auth.php';

app/View/Components/BaseLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class BaseLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render()
    {
        if (theme()->getOption('layout', 'base') === 'docs') {
            return view('layout.docs.master');
        }

        return theme()->getView('layout.master');
    }
}

resources/views/pages/customer-url.blade.php
<link rel="stylesheet" type="text/css" href="{{asset('/')}}demo2/css/style.bundle.css" />
<link rel="stylesheet" type="text/css" href="{{asset('/')}}demo2/plugins/global/plugins.bundle.css" />
<link rel="stylesheet" type="text/css" href="{{asset('/')}}assets/css/customization-image.css" />
<link rel="stylesheet" type="text/css" href="{{asset('/')}}assets/css/lightbox.min.css" />
<link rel="stylesheet" type="text/css" href="{{asset('/')}}assets/css/custom-checkbox.css" />
<script src="{{asset('/')}}assets/js/lightbox-plus-jquery.min.js"></script>

<style>
    .boxShadow{
        box-shadow: 0px 0px 14px grey !important;
    }
    .downstyle2{
      float: right;
      /* margin: -960px 3px 0px 0px; */
      margin: 0px 0px 0px 5px;
      background-color: lightgray !important;
      position: relative;
    }
    .headTitle span{
        color:#000;font-weight: 700;font-size: 18px;
    }

    .headDate{
        padding: 15px 25px 0px 25px;
        text-align:center;
    }

    .divpic{
        margin-bottom: 15px;
    }

</style>
<br/>
    <div class="headTitle">
    <span>Customer Preview</span>           
    </div><br/>

<div class="outer-grid grid-container">
@if($order->Preview_Media != 'null')               
    @php
    $previewArr = json_decode($order->Preview_Media, true); 
    @endphp

    @if($previewArr)
    @foreach($previewArr as $key => $preview)

        @if($preview['Media_Type']=='Image')

        @if($preview['Customer_Preview']=='Yes')

                <div class="inner-grid img-wraps gPreviewBox_{{$order->ID.$key}} boxShadow" id="gPreviewBox_{{$order->ID.$key}}">
                

                <h6 class="headDate">Date: {{ $preview['Date'] }}</h6>
                

                <a class="example-image-link imgg" href="{{$preview['URL']}}" data-lightbox="example-1" style="width: 100% !important;display: block !important;">
                    <div class="divpic">
                        <img class="example-image" src="{{$preview['URL']}}" alt="image-1" />
                    </div>
                </a>
                <a href="{{$preview['URL']}}" download class="btn btn-icon btn-circle  w-25px h-25px bg-body shadow downstyle2">
                    <i class="bi bi-download"></i>
                </a>

                <div class="form-group">
                    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Notes</label> 

                    <div class="col-sm-12" id="gpdivnote_{{$order->ID.$preview['ID']}}" style="margin-bottom: 10px;margin-top: -7px;">							
                        <span class="form-control form-control-sm readable" id="gpnoteUp_{{$order->ID.$preview['ID']}}" style="width: 122%;">{{$preview['Notes']}}</span>							
                    </div>
                </div><br><br>
            </div>
        @endif
        @endif

        @if($preview['Media_Type']=='Video')
        @if($preview['Customer_Preview']=='Yes')

            <div class="inner-grid img-wraps gPreviewBox_{{$order->ID.$key}} boxShadow" id="gPreviewBox_{{$order->ID.$key}}" >

               

                <h6 class="headDate">Date: {{ $preview['Date'] }}</h6>                           
                
                <div class="divpic" style="padding-bottom: 10px;">
                    <video width="100%" controls class="preview-vid" >
                        <source class="example-image" src="{{$preview['URL']}}" type="video/mp4">
                    </video>
                </div>

                <div class="form-group">
                    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Notes</label>

                    <div class="col-sm-12" id="gpdivnote_{{$order->ID.$preview['ID']}}" style="margin-bottom: 10px;margin-top: -7px;">							
                        <span class="form-control form-control-sm readable" id="gpnoteUp_{{$order->ID.$preview['ID']}}" style="width: 122%;">{{$preview['Notes']}}</span>							
                    </div>
                </div><br><br>
                
            </div>
        @endif
        @endif

    @endforeach
    @endif

@else
<h5 style="text-align:center;">Customer Preview Not Found.</h5>
@endif
</div>

resources/views/pages/index.blade.php
<x-base-layout>

    <!--begin::Row-->
    <div class="row gy-5 g-xl-8">
        <!--begin::Col-->
        <div class="col-xxl-4">
            {{ theme()->getView('partials/widgets/mixed/_widget-2', array('class' => 'card-xxl-stretch', 'chartColor' => 'danger', 'chartHeight' => '200px')) }}
        </div>
        <!--end::Col-->

        <!--begin::Col-->
        <div class="col-xxl-4">
            {{ theme()->getView('partials/widgets/lists/_widget-5', array('class' => 'card-xxl-stretch')) }}
        </div>
        <!--end::Col-->

        <!--begin::Col-->
        <div class="col-xxl-4">
            {{ theme()->getView('partials/widgets/mixed/_widget-7', array('class' => 'card-xxl-stretch-50 mb-5 mb-xl-8', 'chartColor' => 'primary', 'chartHeight' => '150px')) }}

            {{ theme()->getView('partials/widgets/mixed/_widget-10', array('class' => 'card-xxl-stretch-50 mb-5 mb-xl-8', 'chartColor' => 'primary', 'chartHeight' => '175px')) }}
        </div>
        <!--end::Col-->
    </div>
    <!--end::Row-->

    <!--begin::Row-->
    <div class="row gy-5 gx-xl-8">
        <!--begin::Col-->
        <div class="col-xxl-4">
            {{ theme()->getView('partials/widgets/lists/_widget-3', array('class' => 'card-xxl-stretch mb-xl-3')) }}
        </div>
        <!--end::Col-->

        <!--begin::Col-->
        <div class="col-xl-8">
            {{ theme()->getView('partials/widgets/tables/_widget-9', array('class' => 'card-xxl-stretch mb-5 mb-xl-8')) }}
        </div>
        <!--end::Col-->
    </div>
    <!--end::Row-->

    <!--begin::Row-->
    <div class="row gy-5 g-xl-8">
        <!--begin::Col-->
        <div class="col-xl-4">
            {{ theme()->getView('partials/widgets/lists/_widget-2', array('class' => 'card-xl-stretch mb-xl-8')) }}
        </div>
        <!--end::Col-->

        <!--begin::Col-->
        <div class="col-xl-4">
            {{ theme()->getView('partials/widgets/lists/_widget-6', array('class' => 'card-xl-stretch mb-xl-8')) }}
        </div>
        <!--end::Col-->

        <!--begin::Col-->
        <div class="col-xl-4">
            {{ theme()->getView('partials/widgets/lists/_widget-4', array('class' => 'card-xl-stretch mb-5 mb-xl-8', 'items' => '5')) }}
        </div>
        <!--end::Col-->
    </div>
    <!--end::Row-->

    <!--begin::Row-->
    <div class="row g-5 gx-xxl-8">
        <!--begin::Col-->
        <div class="col-xxl-4">
            {{ theme()->getView('partials/widgets/mixed/_widget-5', array('class' => 'card-xxl-stretch mb-xl-3', 'chartColor' => 'success', 'chartHeight' => '150px')) }}
        </div>
        <!--end::Col-->

        <!--begin::Col-->
        <div class="col-xxl-8">
            {{ theme()->getView('partials/widgets/tables/_widget-5', array('class' => 'card-xxl-stretch mb-5 mb-xxl-8')) }}
        </div>
        <!--end::Col-->
    </div>
    <!--end::Row-->

</x-base-layout>